# Generated by Django 3.0.7 on 2020-06-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this client', max_length=100)),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Deliver email/sms notifications to users associated with this client')),
                ('inactive', models.BooleanField(default=False, help_text='Mark old clients inactive to keep data w/out deleting')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
